# Generated by Django 3.0.9 on 2020-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201022_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('COLECTOR', 'Collector')], default='CUSTOMER', max_length=50, verbose_name='Type'),
        ),
    ]
