# Generated by Django 3.0.9 on 2020-11-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('COLECTOR', 'Collector')], max_length=50, verbose_name='Type'),
        ),
    ]
