# Generated by Django 3.0.9 on 2020-11-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201102_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_collector',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('COLECTOR', 'Collector')], default='CUSTOMER', max_length=50, verbose_name='Type'),
        ),
    ]
